# Generated by Django 2.0.4 on 2018-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Futbolcu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='adı')),
                ('pozisyon', models.TextField()),
                ('dogum_tarihi', models.TextField()),
                ('yas', models.TextField()),
                ('boy', models.TextField()),
                ('ayak', models.TextField()),
                ('takima_giris', models.TextField()),
                ('sozlesme_son', models.TextField()),
                ('deger', models.TextField()),
                ('takim', models.TextField()),
            ],
        ),
    ]
