# Generated by Django 2.0.4 on 2018-04-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolcu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbolcu',
            name='ayak',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='boy',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='deger',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='dogum_tarihi',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='pozisyon',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='sozlesme_son',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='takim',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='takima_giris',
        ),
        migrations.RemoveField(
            model_name='futbolcu',
            name='yas',
        ),
    ]
